name: Build Device Image

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target Board'
        required: true
        default: 'XIAO_ESP32C3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Firmware
        uses: nanoframework/nanoframework-images-action-artifacts@main
        with:
          target: ${{ github.event.inputs.target }}
          branch: 'main'
